### ISSUE TITLE
Error: Invalid parameter package_settings

### ISSUE THREAD

**Issue by 20after4** [ptomulik/puppet-backport_package_settings#1]
It seems like the package resource is parsed before package_settings is loaded, at least on puppet 3.4.3, I get the following:

`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter package_settings`

Note: the plugin did get sync'd but it doesn't seem like it's loaded soon enough.

**Comment by ptomulik** [comment]
I worked on this module long long ago, so it's quite hard to even recall what it's about :). Could you show, how this module is used in your project? AFAIR in addition to "installing" it, an appropriate "require" statement is required to make it effective. Moreover, the puppet-backport_package_settings  is for those, who implement new package providers, not for users. IIRC, extending existing package providers is impossible without modifying their code.

**Comment by ptomulik** [comment]
If you run FreeBSD, could you try the [portsng](https://forge.puppetlabs.com/ptomulik/portsng) module? It makes use of the puppet-backport_package_settings, and was pretty well tested, so you may quickly verify whether it works on your installation. Perhaps, something changed on the OS side, rendering the module unusable?

**Comment by ptomulik** [comment]
@20after4, Any feedback?

**Comment by 20after4** [comment]
@ptomulik: I ended up using install_options parameter instead of package_settings. It's not ideal but it works. I guess this issue can be closed. Thank you for trying to help!

**Comment by ptomulik** [comment]
@20after4, I'm glad to hear you've found a workaround. Could you tell, maybe, what OS and package provider you were using? I'd like to try to reproduce the issue, or draw some constructive conclusions.
